name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- synapse
- refs/heads/synapse
pr:
- main
- synapse

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'x64'
  major: 0
  minor: 6
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)
  fhirToDatalakeInstanceName: testfhirtodatalake
  dicomToDatalakeInstanceName: testdicomtodatalake
  synapseWorkspaceName: testcisynapseworkspace
  fhirToDatalakeStorageAccountName: testfhirtodoglaw6s6zpluk
  dicomToDatalakeStorageAccountName: testdicomtozrv3ddtm6vwkw
  imageName: healthdatatodatalake

stages:
- stage: Build
  - job: BuildFhirToDataLake
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
    - template: FhirToDataLake/azurepipelines/ci.yml

- stage: OverallTest
  condition: succeeded()
  jobs:
  - job: PrepareTestEnvironment
    pool:
      vmImage: 'ubuntu-22.04'
    steps:
    - template: FhirToDataLake/azurepipelines/OverallTest/set-environment.yml

  - job: RunFhirToSynapseOverallTest
    dependsOn: PrepareTestEnvironment
    condition: succeeded()
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: FhirToDataLake/azurepipelines/OverallTest/fhirtosynapse-e2e-test.yml

  - job: RunDicomToSynapseOverallTest
    dependsOn: PrepareTestEnvironment
    condition: succeeded()
    pool:
      vmImage: 'windows-latest'
    steps:
    - template: FhirToDataLake/azurepipelines/OverallTest/dicomtosynapse-e2e-test.yml

