name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- synapse
- refs/heads/synapse
pr:
- main
- synapse

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'x64'
  major: 0
  minor: 4
  patch: 0
  buildnum: $[counter(format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)
  azureFunctionName: testanalyticspipeline
  synapseWorkspaceName: testcisynapseworkspace
  storageAccountName: testanalytihv4hqces73r4o

stages:
- stage: Release
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: RunSynapseE2ETest
    steps:
    - template: FhirToDataLake/azurepipelines/synapse-e2e-test.yml

