name: $(Date:yyyyMMdd)$(Rev:.r)

trigger:
- main
- synapse
- refs/heads/synapse
pr:
- main
- synapse

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'x64'
  major: 0
  minor: 4
  patch: 1
  buildnum: $[counter(format('{0}.{1}.{2}', variables['major'], variables['minor'], variables['patch']), 1)]
  version: $(major).$(minor).$(patch).$(buildnum)
  azureFunctionName: testanalyticspipeline
  synapseWorkspaceName: testcisynapseworkspace
  storageAccountName: testanalytihv4hqces73r4o

stages:
- stage: Build
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: BuildFhirToCdm
    steps:
    - template: FhirToCdm/build.yml

  - job: BuildFhirToDataLake
    steps:
    - template: FhirToDataLake/build.yml

- stage: Release
  condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/heads/releases/'))
  pool:
    vmImage: 'windows-latest'
  jobs:
  - job: RunSynapseE2ETest
    steps:
    - template: FhirToDataLake/synapse-e2e-test.yml

  - job: PublishFhirToCdm
    dependsOn: RunSynapseE2ETest
    condition: succeeded()
    steps:
    - template: FhirToCdm/publish.yml

  - job: PublishArtifactsToGitHub
    dependsOn: PublishFhirToCdm
    condition: succeeded()
    steps:
    - template: publish.yml
